design.pdf: \
	design.tex \
	titlepage.tex \
	intermoduledependencies.tex \
	dbmancd.png svlogiccd.png \
	interprocessdependencies.tex \
	interfacedescriptions.tex \
	introduction.tex \
	versionhistory.tex

	xelatex design.tex
